# Fake external service image
image:
  repository: tccr.io/truecharts/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:5391a9572fcfda2ec5a9df99e08d4772f13635041eccfa61e57d49935486d9db

service:
  main:
    type: ExternalIP
    externalIP: "1.1.1.1"
    useSlice: false
    ports:
      main:
        protocol: https
        port: 10003
        # Target port is the port of the "external service"
        # Defaults to "port" if not set

workload:
  main:
    enabled: false
    podSpec:
      containers:
        main:
          env: {}

portal:
  open:
    enabled: true
