image:
  repository: tccr.io/truecharts/doublecommander
  pullPolicy: IfNotPresent
  tag: latest@sha256:1804dd87c17bfacf2c96130f1eb11a2c5dc5c51af6d173d3ddc3e45c11928c87

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10034
        targetPort: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            capabilities:
              add:
                - SYS_CHROOT
                - KILL
                - NET_BIND_SERVICE
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
