image:
  repository: tccr.io/truecharts/wizarr
  pullPolicy: IfNotPresent
  tag: v3.0.1@sha256:ca6e0afe43870499b1768b3f37b243352642ac71a4a920d537867814b10f6794

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5690
        port: 10596

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
              type: http
            readiness:
              path: "/"
              type: http
            startup:
              path: "/"
              type: http
          env:
            APP_URL: "http://localhost:{{ .Values.service.main.ports.main.port }}"
            DISABLE_BUILTIN_AUTH: false
            ALLOW_BUG_REPORTING: false

persistence:
  database:
    enabled: true
    mountPath: /data/database

portal:
  open:
    enabled: true
