image:
  repository: tccr.io/truecharts/unifi-poller
  pullPolicy: IfNotPresent
  tag: v2.8.3@sha256:3fc37617b16d6310e1671274261886120c2113170fabf74fa0e1de4a88de9ade
service:
  main:
    ports:
      main:
        port: 9130
metrics:
  main:
    enabled: true
    type: "servicemonitor"
    endpoints:
      - port: main
        path: /metrics
    prometheusRule:
      enabled: false

portal:
  open:
    enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /
            readiness:
              path: /
            startup:
              path: /
          env:
            # UP_UNIFI_DEFAULT_URL: "https://127.0.0.1:8443"
            # UP_UNIFI_DEFAULT_USER: "unifipoller"
            # UP_UNIFI_DEFAULT_PASS: "unifipoller"
            UP_PROMETHEUS_DISABLE: false
